### ISSUE TITLE
[US-330] Registration success

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#101]
## Value Statement

As a user I want to be able to see an information that my registration was successful. I then want to be able to login.

## Description

![userStory330](https://user-images.githubusercontent.com/89029415/138588885-50b8e4da-a5ab-4023-97df-eb28ab2486d5.png)

## Acceptance Criteria

- success message
- Link to Login

## Subtasks

- [ ] Create feature branch
- [ ] Create component
- [ ] Write component tests
- [ ] Add component to App
- [ ] Add missing styling

## Complexity

low
