### ISSUE TITLE
[US-350] Unwatched Movies overview

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#103]
## Value Statement

As a user I want to be able to remove movies from my unwatched movies list if I now have seen it. 

## Description

![userStory350](https://user-images.githubusercontent.com/89029415/138589256-b7beb314-d701-4c5d-9c9b-ad78f607162f.png)

## Acceptance Criteria

- list of unwatched movies
- Button to remove it from the list

## Subtasks

- [ ] Create feature branch
- [ ] Create component
- [ ] Write component tests
- [ ] Add component to App
- [ ] Add missing styling

## Complexity

Medium
