### ISSUE TITLE
[US-200] Add functionality to register form

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#16]
## Value Statement

As a user I now want to be able to have the functionality to create an account. If the registration had an error I want to get an error message (not detailed yet).

## Description

![userStory230](https://user-images.githubusercontent.com/89029415/136385070-6f4dbf58-8272-49c9-954c-aa378f492233.png)

## Acceptance Criteria

- Form gets an onSubmit function
- Success message
- Error message (no details yet)

## Subtasks

- [x] Create feature branch
- [x] Create onSubmit functionality
- [x] Write component tests

## Complexity

medium
