### ISSUE TITLE
[US-220] Add functionality to login

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#18]
## Value Statement

As a user I now want to be able to have the functionality to log into the app. If the login had an error I want to get an error message (not detailed yet).

## Description

![userStory250](https://user-images.githubusercontent.com/89029415/136387052-74fc4499-7710-4efb-af80-fb5ca0f24c70.png)

## Acceptance Criteria

- Login Form gets an onSubmit function
- Success message
- Error message (no details yet)

## Subtasks

- [x] Create feature branch
- [x] Create onSubmit functionality
- [x] Write component tests

## Complexity

medium
