### ISSUE TITLE
[US-221] Add corresponding error message on login form

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#19]
## Value Statement

As a user I want to get exact feedback on what went wrong while trying to login

## Description

![userStory250](https://user-images.githubusercontent.com/89029415/136387332-85055171-f455-42e0-8343-bd6653ca2dfe.png)

## Acceptance Criteria

- Show corresponding error message

## Subtasks

- [x] Create feature branch
- [x] Write component tests
- [x] Add missing styles

## Complexity

Low
