### ISSUE TITLE
[US-270] Add voting component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#20]
## Value Statement

As a user I want to see a layout of the voting form. I don't need the functionality to work yet

## Description

![userStory270](https://user-images.githubusercontent.com/89029415/136390051-6a6f5262-1677-4ed2-96b4-e1e131cb0e64.png)

## Acceptance Criteria

- Show 2 movie cards
- Show voting buttons (no functionality)
- Show "I don't know the movie(s)" buttons (no functionality)

## Subtasks

- [x] Create feature branch
- [x] Create layout of voting component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

Medium
