### ISSUE TITLE
[US-260] Movie card component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#21]
## Value Statement

As a user I want to see a layout of the movie card. 

## Description

![userStory260](https://user-images.githubusercontent.com/89029415/136391091-7ae74bca-b0ba-49ce-bdb5-b4a5d1a87c2a.png)

## Acceptance Criteria

- Shows a picture/poster
- Shows the title
- Shows the year
- Shows the category

## Subtasks

- [x] Create feature branch
- [x] Create layout of movie card component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

Low
