### ISSUE TITLE
[US-273] Add GET to voting component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#22]
## Value Statement

As a user I want to see two different movies that are loaded from the database via the api.

## Description

![userStory270](https://user-images.githubusercontent.com/89029415/136390051-6a6f5262-1677-4ed2-96b4-e1e131cb0e64.png)

## Acceptance Criteria

- Connection to api
- Show 2 movie cards containing the information of the loaded data

## Subtasks

- [x] Create feature branch
- [x] Add functionality to load movies from the api
- [x] Write component tests

## Complexity

Medium
