### ISSUE TITLE
[US-275] Add voting functionality to voting component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#23]
## Value Statement

As a user I want to be able to vote on which movie I like more. After I clicked one of the specific buttons I want to get to the next voting option.

## Description

![userStory270](https://user-images.githubusercontent.com/89029415/136390051-6a6f5262-1677-4ed2-96b4-e1e131cb0e64.png)

## Acceptance Criteria

- Connection to api
- Send voting result to the database
- Go to the next voting

## Subtasks

- [x] Create feature branch
- [x] Add functionality to submit voting result to the api
- [x] Write component tests

## Complexity

Medium
