### ISSUE TITLE
[US-280] Add "I dont know" functionality to voting component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#24]
## Value Statement

As a user I want to be able to tell the app that I do not know a movie or even both movies. After I clicked the button I want to get to the next voting.

## Description

![userStory270](https://user-images.githubusercontent.com/89029415/136390051-6a6f5262-1677-4ed2-96b4-e1e131cb0e64.png)

## Acceptance Criteria

- Connection to api
- Check user isLoggedIn
- Send 'I dont know' to the database
- Go to the next voting

## Subtasks

- [x] Create feature branch
- [x] Add functionality to check if the user is logged in
- [x] Add functionality to submit 'I dont know' result to the api
- [x] Write component tests

## Complexity

Medium
