### ISSUE TITLE
[US-305] Database connection for toplist component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#26]
## Value Statement

As a user I want to be able see the top 100 of all movies sorted by points from the database

## Description

![userStory300](https://user-images.githubusercontent.com/89029415/136399628-19436364-fbb6-4410-9713-354d94cbdb71.png)

## Acceptance Criteria

- Loads data from database

## Subtasks

- [x] Create feature branch
- [x] GET data from database
- [x] Write component tests

## Complexity

Medium
