### ISSUE TITLE
[US-271] Add link in navigation to voting

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#27]
## Value Statement

As a user I want to be able to get to the voting by clicking the corresponding button in the navigation. 

## Description

![userStory002](https://user-images.githubusercontent.com/89029415/136288314-ce69dd2e-169d-4230-9982-ce30da425fed.png)

## Acceptance Criteria

- Add a Link to voting in the navigation
- After clicking the link the voting page will be displayed

## Subtasks

- [ ] Create feature branch
- [ ] Add Link to navigation
- [ ] Write component tests

## Complexity

Medium
