### ISSUE TITLE
[US-900] Styling to Header component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#28]
## Value Statement

As a user I want to see a nice Header which helps me to identify that I am at the right place

## Description

![userStory900](https://user-images.githubusercontent.com/89029415/136402888-fa8e7e65-743c-484b-acff-7909a1406b06.png)

## Acceptance Criteria

- Add design to the Header component

## Subtasks

- [ ] Create feature branch
- [ ] Add design to header component
- [ ] Write component tests

## Complexity

Low
