### ISSUE TITLE
[US-301] Add link to Toplist in navigation

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#29]
## Value Statement

As a user I want to be able to get to the toplist by clicking the corresponding button in the navigation. 

## Description

![userStory002](https://user-images.githubusercontent.com/89029415/136288314-ce69dd2e-169d-4230-9982-ce30da425fed.png)

## Acceptance Criteria

- Add a Link to toplist in the navigation
- After clicking the link the toplist page will be displayed

## Subtasks

- [x] Create feature branch
- [x] Add Link to navigation
- [x] Write component tests

## Complexity

Medium
