### ISSUE TITLE
[US-002] Landing Page components

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#3]
## Value Statement

As a user I want to get a little introduction to what the app is about. 

## Description

![userStory002](https://user-images.githubusercontent.com/89029415/136288314-ce69dd2e-169d-4230-9982-ce30da425fed.png)

## Acceptance Criteria

- Shows a Header (Contains just a h1)
- Shows a Main
- Shows a Footer/Navigation (not functional yet!)

## Subtasks

- [x] Create feature branch
- [x] Create header component
- [x] Create Footer / Navigation component
- [x] Create a home component
- [x] Write component tests
- [x] Add components to app
- [x] Add missing styles

## Complexity

Medium
