### ISSUE TITLE
[US-100] Add profile component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#30]
## Value Statement

As a user I want to be able to see my profile.

## Description

![userStory100](https://user-images.githubusercontent.com/89029415/136406569-fb2f36bd-f253-4fc7-b191-2b7c405ff894.png)

## Acceptance Criteria

- Add a text for username and email
- Add a edit button (not functional)
- Add a logout button (not functional)
- Add a delete button (not functional)

## Subtasks

- [x] Create feature branch
- [x] Create profile component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

medium
