### ISSUE TITLE
[US-101] Add link to Profile in navigation

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#31]
## Value Statement

As a user I want to be able to get to the profile by clicking the corresponding button in the navigation. 

## Description

![userStory002](https://user-images.githubusercontent.com/89029415/136407821-154cbe39-fe1c-4db4-bfc1-d15ef966c882.png)

## Acceptance Criteria

- Add a Link to profile in the navigation
- After clicking the link the profile page will be displayed

## Subtasks

- [x] Create feature branch
- [x] Add Link to navigation
- [x] Write component tests

## Complexity

Medium
