### ISSUE TITLE
[AS-100] Add movie component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#35]
## Value Statement

As a admin I want to be able to add a movie to the database. Right now I just want the form and not the functionality yet

## Description

![adminStory100](https://user-images.githubusercontent.com/89029415/136822476-6910d35f-bf8f-4c72-a42b-874d6ba0e3c3.png)

## Acceptance Criteria

- Shows a form
- Has an title
- Has an input for tmdb_id
- Has an button to submit

## Subtasks

- [x] Create feature branch
- [x] Create add movie component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

Medium
