### ISSUE TITLE
[US-230] User logged in views

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#37]
## Value Statement

As a user I should only be able to see certain content if I am logged in. The content that I am allowed to see while not logged in is 'home' and 'toplist', for everything else I need to be logged in.

## Description

![userStory230](https://user-images.githubusercontent.com/89029415/136426006-1d32d1b0-e3a5-439d-bf36-240d22e8e994.png)

## Acceptance Criteria

- Only show pages if the user is logged in
- Show message for pages that the user needs to be logged in for

## Subtasks

- [x] Create feature branch
- [x] Create NotLoggedIn component
- [x] Create corresponding functionality
- [x] Write component tests

## Complexity

medium
