### ISSUE TITLE
[US-250] Delete Account

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#39]
## Value Statement

As a user I want to be able to delete my account. I can use the **delete button** in the profile.

## Description

![userStory245](https://user-images.githubusercontent.com/89029415/136430777-73c4cff0-a622-43c3-bc49-ee847cab88d2.png)

## Acceptance Criteria

- onClick functionality
- function to delete the account
- redirect to home

## Subtasks

- [x] Create feature branch
- [x] Create corresponding functionality
- [x] Write component tests

## Complexity

medium
