### ISSUE TITLE
[US-060] Login form component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#4]
## Value Statement

As a user I want to be able to log into the app. So I need a form to do it.

## Description

![userStory003](https://user-images.githubusercontent.com/89029415/136290276-8322a40d-df40-48c2-a2ef-592bde1eb1e7.png)

## Acceptance Criteria

- Login form
- Input field for Username
- Input field for Password
- Submit Button

## Subtasks

- [x] Create feature branch
- [x] Create form component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

medium
