### ISSUE TITLE
[US-240] Edit user data form component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#40]
## Value Statement

As a user I want to be able to edit the data of my account. For this I need a formular. If I click on the submit button I want to submit the data and PUT them into the database. If it was not successful, I want to receive an error message. If it was successful I want to be redirected to the profile.

## Description

![userStory240](https://user-images.githubusercontent.com/89029415/136431516-0213d8bc-bce7-4fe8-9f5d-bc8727c68057.png)

## Acceptance Criteria

- Edit form
- Input field for email
- Input field for password
- Input field for password retype
- Submit Button
- Error message

## Subtasks

- [x] Create feature branch
- [x] Create edit form component
- [x] Add functionality
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

medium
