### ISSUE TITLE
[US-020] Error Card Component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#41]
## Value Statement

As a user I want to see what error occured if something went wrong. For this I want to see a little information with a title and some information text.

## Description

![userStory020](https://user-images.githubusercontent.com/89029415/136433269-2279e042-9a0d-4cc3-a348-c61c7959b007.png)

## Acceptance Criteria

- Error Card
- Shows a title
- Shows an information text

## Subtasks

- [x] Create feature branch
- [x] Create error card component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

low
