### ISSUE TITLE
[AS-140] Add Movies Overview Component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#50]
## Value Statement

As an admin I want to see a list of all movies that are in the database at the moment. A number that shows the count should be displayed, too.

## Description

![adminStory140](https://user-images.githubusercontent.com/89029415/136823736-b85962b4-190f-4a26-8cfd-96164fd4699c.png)

## Acceptance Criteria

- Info about moviecount
- Shows a list of movies in the database

## Subtasks

- [x] Create feature branch
- [x] Create overview component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

medium
