### ISSUE TITLE
[US-025] Success Card Component

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#53]
## Value Statement

As a user I want to see what error occured if something went wrong. For this I want to see a little information with a title and some information text.

## Acceptance Criteria

- Error Card
- Shows a title
- Shows an information text

## Subtasks

- [x] Create feature branch
- [x] Create error card component
- [x] Write component tests
- [x] Add component to app
- [x] Add missing styles

## Complexity

low
