### ISSUE TITLE
[US-026] Button Components

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#54]
## Value Statement

As a user I want to see a button that has an color that indicates what happens when I click on it. I want a red, blue and green button.

## Description

![userStory026](https://user-images.githubusercontent.com/89029415/137013637-d72fbd22-61cc-498c-86f2-481ef7f2b6ff.png)

## Acceptance Criteria

- Button
- Shows a message
- Has a specific color

## Subtasks

- [x] Create feature branch
- [x] Create button components
- [x] Write component tests
- [x] Add components to app
- [x] Add missing styles

## Complexity

low
