### ISSUE TITLE
[US-027] LoadingSpinner

### ISSUE THREAD

**Issue by StefanBehring** [StefanBehring/capstone-project#66]
## Value Statement

As a user I want to get feedback if the page is currently doing something. As oftentimes I will wait for the page to be rendered, I want to see some visual feedback that shows me that something is happening.

## Description

![userStory025](https://user-images.githubusercontent.com/89029415/137013154-5af8af96-db54-45c2-821d-936da2e6e04e.png)

## Acceptance Criteria

- LoadingSpinner
- Shows 3 Circles rotating and growing

## Subtasks

- [x] Create feature branch
- [x] Create LoadingSpinner component
- [x] Add component to app
- [x] Add missing styles

## Complexity

low
